language: cpp

compiler:
  - gcc

before_install:

before_script:
  - cd Boost
  - make
  - cd ../FMU


script: make

after_success:


branches:
  only:
    - Master

notifications:
  email: false

env:

os:
  - linux
