language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

before_install:
  - export CXX="g++-4.9"
  - export CC="g++-4.9"
  - export LD="g++-4.9"
  # download submodules
  - git submodule update --init --recursive

before_script:
  - cd Boost
  - make


script:
  - cd ../FMU
  - make
  - cd ../tests
  - make
  - ./unittest

after_success:

branches:
  only:
    - Master

notifications:
  email: false

env:

os:
  - linux
