language: cpp

#sudo: true

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9

before_install:
  - export CXX="g++-4.9" CC="gcc-4.9";
  # download submodules
  - git submodule update --init --recursive

before_script:
  - cd Boost
  - make
  - cd ../FMU

script: make

after_success:

branches:
  only:
    - Master

notifications:
  email: false

env:

os:
  - linux
