language: cpp

sudo: required
dist: trusty

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - gcc-4.9
    - cmake
    # Need travis to update from precise
    - gcc-mingw-w64-i686
    - g++-mingw-w64-i686
    - binutils-mingw-w64-i686
    - gcc-mingw-w64-x86-64
    - g++-mingw-w64-x86-64
    - binutils-mingw-w64-x86-64

before_install:
  - export CXX="g++-4.9"
  - export CC="gcc-4.9"
  - export LD="g++-4.9"
  # download submodules
  - git submodule update --init --recursive

before_script:
  - mkdir FMU/build
  - mkdir FMU/build32
  - mkdir FMU/build64
  - cd Boost
  - make

script:
  - cd ../FMU/build
  - cmake -Dtests=ON ../
  - make
  - mv runUnitTests ../
  - cd ../
  #- ./runUnitTests
  - cd ./build64
  - cmake -DCrossCompile64=ON ../
  - make
  - mv libFMI.dll libFMI64.dll
  - cd ../build32
  - cmake -DCrossCompile32=ON ../
  - make
  - mv libFMI.dll libFMI32.dll

after_success:

branches:
  only:
    - Master

notifications:
  email: false

env:

os:
  - linux


deploy:
  provider: releases
  api-key: "e9ce95182cc7c302f0f74029411c7d912a6afcfa "
  file:
    - "FMU/build/libFMI.so"
    #- "FMU/build32/libFMI32.dll"
    #- "FMU/build64/libFMI64.dll"
  skip_cleanup: true
