language: cpp

sudo: true

compiler:
  - gcc

before_install:
  # make sure gcc is up to date
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get -qq install g++-4.9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 80
  - g++ --version
  # download submodules
  - git submodule update --init --recursive

before_script:
  - cd Boost
  - make
  - cd ../FMU


script: make

after_success:


branches:
  only:
    - Master

notifications:
  email: false

env:

os:
  - linux
